[package]
name = "lesbin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.28.1"
itertools = "0.13.0"
ratatui = "0.29.0"

[profile.release]
panic = "abort"
strip = true
lto = true
